module.exports = [
    {
        city: "Delhi",
        latitude: 28.61,
        longitude: 77.23,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "admin",
        populatitudeion: 32226000,
        populatitudeion_proper: 16753235
    },
    {
        city: "Mumbai",
        latitude: 19.0761,
        longitude: 72.8775,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "admin",
        populatitudeion: 24973000,
        populatitudeion_proper: 12478447
    },
    {
        city: "Kolkāta",
        latitude: 22.5675,
        longitude: 88.37,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "admin",
        populatitudeion: 18502000,
        populatitudeion_proper: 4496694
    },
    {
        city: "Bangalore",
        latitude: 12.9789,
        longitude: 77.5917,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "admin",
        populatitudeion: 15386000,
        populatitudeion_proper: 8443675
    },
    {
        city: "Chennai",
        latitude: 13.0825,
        longitude: 80.275,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "admin",
        populatitudeion: 12395000,
        populatitudeion_proper: 6727000
    },
    {
        city: "Hyderābād",
        latitude: 17.3617,
        longitude: 78.4747,
        country: "India",
        iso2: "IN",
        admin_name: "Telangāna",
        capital: "admin",
        populatitudeion: 10494000,
        populatitudeion_proper: 6993262
    },
    {
        city: "Pune",
        latitude: 18.5203,
        longitude: 73.8567,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 8231000,
        populatitudeion_proper: 3124458
    },
    {
        city: "Ahmedabad",
        latitude: 23.0225,
        longitude: 72.5714,
        country: "India",
        iso2: "IN",
        admin_name: "Gujarāt",
        capital: "minor",
        populatitudeion: 8009000,
        populatitudeion_proper: 5570585
    },
    {
        city: "Sūrat",
        latitude: 21.1702,
        longitude: 72.8311,
        country: "India",
        iso2: "IN",
        admin_name: "Gujarāt",
        capital: "",
        populatitudeion: 6538000,
        populatitudeion_proper: 4466826
    },
    {
        city: "Lucknow",
        latitude: 26.85,
        longitude: 80.95,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "admin",
        populatitudeion: 3382000,
        populatitudeion_proper: 3382000
    },
    {
        city: "Jaipur",
        latitude: 26.9,
        longitude: 75.8,
        country: "India",
        iso2: "IN",
        admin_name: "Rājasthān",
        capital: "admin",
        populatitudeion: 3073350,
        populatitudeion_proper: 3073350
    },
    {
        city: "Kanpur",
        latitude: 26.4499,
        longitude: 80.3319,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 2701324,
        populatitudeion_proper: 2701324
    },
    {
        city: "Mirzāpur",
        latitude: 25.146,
        longitude: 82.569,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 2496970,
        populatitudeion_proper: 2496970
    },
    {
        city: "Nāgpur",
        latitude: 21.1497,
        longitude: 79.0806,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 2405665,
        populatitudeion_proper: 2405665
    },
    {
        city: "Ghāziābād",
        latitude: 28.67,
        longitude: 77.42,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 2375820,
        populatitudeion_proper: 2375820
    },
    {
        city: "Supaul",
        latitude: 26.126,
        longitude: 86.605,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2229076,
        populatitudeion_proper: 2229076
    },
    {
        city: "Vadodara",
        latitude: 22.3,
        longitude: 73.2,
        country: "India",
        iso2: "IN",
        admin_name: "Gujarāt",
        capital: "",
        populatitudeion: 2065771,
        populatitudeion_proper: 2065771
    },
    {
        city: "Rājkot",
        latitude: 22.3,
        longitude: 70.7833,
        country: "India",
        iso2: "IN",
        admin_name: "Gujarāt",
        capital: "",
        populatitudeion: 2043000,
        populatitudeion_proper: 2043000
    },
    {
        city: "Vishākhapatnam",
        latitude: 17.7042,
        longitude: 83.2978,
        country: "India",
        iso2: "IN",
        admin_name: "Andhra Pradesh",
        capital: "",
        populatitudeion: 2035922,
        populatitudeion_proper: 2035922
    },
    {
        city: "Indore",
        latitude: 22.7167,
        longitude: 75.8472,
        country: "India",
        iso2: "IN",
        admin_name: "Madhya Pradesh",
        capital: "",
        populatitudeion: 1994397,
        populatitudeion_proper: 1994397
    },
    {
        city: "Thāne",
        latitude: 19.1972,
        longitude: 72.9722,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 1886941,
        populatitudeion_proper: 1886941
    },
    {
        city: "Bhopāl",
        latitude: 23.2599,
        longitude: 77.4126,
        country: "India",
        iso2: "IN",
        admin_name: "Madhya Pradesh",
        capital: "admin",
        populatitudeion: 1798218,
        populatitudeion_proper: 1798218
    },
    {
        city: "Pimpri-Chinchwad",
        latitude: 18.6186,
        longitude: 73.8037,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 1727692,
        populatitudeion_proper: 1727692
    },
    {
        city: "Patna",
        latitude: 25.594,
        longitude: 85.1376,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "admin",
        populatitudeion: 1684222,
        populatitudeion_proper: 1684222
    },
    {
        city: "Bilāspur",
        latitude: 22.09,
        longitude: 82.15,
        country: "India",
        iso2: "IN",
        admin_name: "Chhattīsgarh",
        capital: "",
        populatitudeion: 1625502,
        populatitudeion_proper: 1625502
    },
    {
        city: "Ludhiāna",
        latitude: 30.91,
        longitude: 75.85,
        country: "India",
        iso2: "IN",
        admin_name: "Punjab",
        capital: "",
        populatitudeion: 1618879,
        populatitudeion_proper: 1618879
    },
    {
        city: "Āgra",
        latitude: 27.18,
        longitude: 78.02,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 1585704,
        populatitudeion_proper: 1585704
    },
    {
        city: "Madurai",
        latitude: 9.9252,
        longitude: 78.1198,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "minor",
        populatitudeion: 1561129,
        populatitudeion_proper: 1561129
    },
    {
        city: "Jamshedpur",
        latitude: 22.7925,
        longitude: 86.1842,
        country: "India",
        iso2: "IN",
        admin_name: "Jhārkhand",
        capital: "",
        populatitudeion: 1558000,
        populatitudeion_proper: 1558000
    },
    {
        city: "Prayagraj",
        latitude: 25.4358,
        longitude: 81.8464,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 1536218,
        populatitudeion_proper: 1536218
    },
    {
        city: "Nāsik",
        latitude: 19.9975,
        longitude: 73.7898,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 1486053,
        populatitudeion_proper: 1486053
    },
    {
        city: "Farīdābād",
        latitude: 28.4211,
        longitude: 77.3078,
        country: "India",
        iso2: "IN",
        admin_name: "Haryāna",
        capital: "",
        populatitudeion: 1414050,
        populatitudeion_proper: 1414050
    },
    {
        city: "Meerut",
        latitude: 28.98,
        longitude: 77.71,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 1305429,
        populatitudeion_proper: 1305429
    },
    {
        city: "Jabalpur",
        latitude: 23.1667,
        longitude: 79.9333,
        country: "India",
        iso2: "IN",
        admin_name: "Madhya Pradesh",
        capital: "",
        populatitudeion: 1267564,
        populatitudeion_proper: 1267564
    },
    {
        city: "Kalyān",
        latitude: 19.2502,
        longitude: 73.1602,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 1246381,
        populatitudeion_proper: 1246381
    },
    {
        city: "Vasai-Virar",
        latitude: 19.3607,
        longitude: 72.7956,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 1221233,
        populatitudeion_proper: 1221233
    },
    {
        city: "Najafgarh",
        latitude: 28.6092,
        longitude: 76.9798,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "",
        populatitudeion: 1203180,
        populatitudeion_proper: 1203180
    },
    {
        city: "Vārānasi",
        latitude: 25.3189,
        longitude: 83.0128,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 1198491,
        populatitudeion_proper: 1198491
    },
    {
        city: "Srīnagar",
        latitude: 34.09,
        longitude: 74.79,
        country: "India",
        iso2: "IN",
        admin_name: "Jammu and Kashmīr",
        capital: "admin",
        populatitudeion: 1180570,
        populatitudeion_proper: 1180570
    },
    {
        city: "Aurangābād",
        latitude: 19.88,
        longitude: 75.32,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 1175116,
        populatitudeion_proper: 1175116
    },
    {
        city: "Dhanbād",
        latitude: 23.7998,
        longitude: 86.4305,
        country: "India",
        iso2: "IN",
        admin_name: "Jhārkhand",
        capital: "",
        populatitudeion: 1162472,
        populatitudeion_proper: 1162472
    },
    {
        city: "Amritsar",
        latitude: 31.64,
        longitude: 74.86,
        country: "India",
        iso2: "IN",
        admin_name: "Punjab",
        capital: "",
        populatitudeion: 1132383,
        populatitudeion_proper: 1132383
    },
    {
        city: "Alīgarh",
        latitude: 27.88,
        longitude: 78.08,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 1131160,
        populatitudeion_proper: 1131160
    },
    {
        city: "Guwāhāti",
        latitude: 26.1722,
        longitude: 91.7458,
        country: "India",
        iso2: "IN",
        admin_name: "Assam",
        capital: "",
        populatitudeion: 1116267,
        populatitudeion_proper: 1116267
    },
    {
        city: "Hāora",
        latitude: 22.58,
        longitude: 88.3294,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 1077075,
        populatitudeion_proper: 1077075
    },
    {
        city: "Rānchi",
        latitude: 23.36,
        longitude: 85.33,
        country: "India",
        iso2: "IN",
        admin_name: "Jhārkhand",
        capital: "admin",
        populatitudeion: 1073440,
        populatitudeion_proper: 1073440
    },
    {
        city: "Gwalior",
        latitude: 26.2124,
        longitude: 78.1772,
        country: "India",
        iso2: "IN",
        admin_name: "Madhya Pradesh",
        capital: "",
        populatitudeion: 1069276,
        populatitudeion_proper: 1069276
    },
    {
        city: "Chandīgarh",
        latitude: 30.75,
        longitude: 76.78,
        country: "India",
        iso2: "IN",
        admin_name: "Chandīgarh",
        capital: "admin",
        populatitudeion: 1055450,
        populatitudeion_proper: 1055450
    },
    {
        city: "Haldwāni",
        latitude: 29.22,
        longitude: 79.52,
        country: "India",
        iso2: "IN",
        admin_name: "Uttarākhand",
        capital: "",
        populatitudeion: 1050000,
        populatitudeion_proper: 1050000
    },
    {
        city: "Vijayavāda",
        latitude: 16.5193,
        longitude: 80.6305,
        country: "India",
        iso2: "IN",
        admin_name: "Andhra Pradesh",
        capital: "",
        populatitudeion: 1048240,
        populatitudeion_proper: 1048240
    },
    {
        city: "Jodhpur",
        latitude: 26.28,
        longitude: 73.02,
        country: "India",
        iso2: "IN",
        admin_name: "Rājasthān",
        capital: "",
        populatitudeion: 1033918,
        populatitudeion_proper: 1033918
    },
    {
        city: "Raipur",
        latitude: 21.2444,
        longitude: 81.6306,
        country: "India",
        iso2: "IN",
        admin_name: "Chhattīsgarh",
        capital: "admin",
        populatitudeion: 1010087,
        populatitudeion_proper: 1010087
    },
    {
        city: "Kota",
        latitude: 25.18,
        longitude: 75.83,
        country: "India",
        iso2: "IN",
        admin_name: "Rājasthān",
        capital: "",
        populatitudeion: 1001694,
        populatitudeion_proper: 1001694
    },
    {
        city: "Bhayandar",
        latitude: 19.29,
        longitude: 72.85,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 809378,
        populatitudeion_proper: 809378
    },
    {
        city: "Loni",
        latitude: 28.75,
        longitude: 77.28,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 516082,
        populatitudeion_proper: 516082
    },
    {
        city: "Ambattūr",
        latitude: 13.1143,
        longitude: 80.1548,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 466205,
        populatitudeion_proper: 466205
    },
    {
        city: "Salt Lake City",
        latitude: 22.61,
        longitude: 88.4,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 403316,
        populatitudeion_proper: 403316
    },
    {
        city: "Bhātpāra",
        latitude: 22.87,
        longitude: 88.41,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 386019,
        populatitudeion_proper: 386019
    },
    {
        city: "Kūkatpalli",
        latitude: 17.4849,
        longitude: 78.4138,
        country: "India",
        iso2: "IN",
        admin_name: "Telangāna",
        capital: "",
        populatitudeion: 385821,
        populatitudeion_proper: 385821
    },
    {
        city: "Dāsarhalli",
        latitude: 13.0465,
        longitude: 77.513,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 349720,
        populatitudeion_proper: 349720
    },
    {
        city: "Muzaffarpur",
        latitude: 26.1225,
        longitude: 85.3906,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 333200,
        populatitudeion_proper: 333200
    },
    {
        city: "Oulgaret",
        latitude: 11.957,
        longitude: 79.7737,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 300104,
        populatitudeion_proper: 300104
    },
    {
        city: "New Delhi",
        latitude: 28.6139,
        longitude: 77.2089,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "primary",
        populatitudeion: 249998,
        populatitudeion_proper: 249998
    },
    {
        city: "Tiruvottiyūr",
        latitude: 13.16,
        longitude: 80.3,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 249446,
        populatitudeion_proper: 249446
    },
    {
        city: "Puducherry",
        latitude: 11.9167,
        longitude: 79.8167,
        country: "India",
        iso2: "IN",
        admin_name: "Puducherry",
        capital: "admin",
        populatitudeion: 244377,
        populatitudeion_proper: 244377
    },
    {
        city: "Byatarayanpur",
        latitude: 13.0659,
        longitude: 77.5922,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 239902,
        populatitudeion_proper: 239902
    },
    {
        city: "Pallāvaram",
        latitude: 12.9675,
        longitude: 80.1491,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 215417,
        populatitudeion_proper: 215417
    },
    {
        city: "Secunderābād",
        latitude: 17.4399,
        longitude: 78.4983,
        country: "India",
        iso2: "IN",
        admin_name: "Telangāna",
        capital: "",
        populatitudeion: 213698,
        populatitudeion_proper: 213698
    },
    {
        city: "Shimla",
        latitude: 31.1033,
        longitude: 77.1722,
        country: "India",
        iso2: "IN",
        admin_name: "Himāchal Pradesh",
        capital: "admin",
        populatitudeion: 206575,
        populatitudeion_proper: 206575
    },
    {
        city: "Puri",
        latitude: 19.8,
        longitude: 85.8167,
        country: "India",
        iso2: "IN",
        admin_name: "Odisha",
        capital: "",
        populatitudeion: 201026,
        populatitudeion_proper: 201026
    },
    {
        city: "Murtazābād",
        latitude: 28.7111,
        longitude: 77.2688,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 189117,
        populatitudeion_proper: 189117
    },
    {
        city: "Shrīrāmpur",
        latitude: 22.75,
        longitude: 88.34,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 181842,
        populatitudeion_proper: 181842
    },
    {
        city: "Chandannagar",
        latitude: 22.87,
        longitude: 88.38,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 166867,
        populatitudeion_proper: 166867
    },
    {
        city: "Sultānpur Mazra",
        latitude: 28.6981,
        longitude: 77.0689,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "",
        populatitudeion: 163716,
        populatitudeion_proper: 163716
    },
    {
        city: "Krishnanagar",
        latitude: 23.4,
        longitude: 88.5,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 153062,
        populatitudeion_proper: 153062
    },
    {
        city: "Bārākpur",
        latitude: 22.76,
        longitude: 88.37,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 152783,
        populatitudeion_proper: 152783
    },
    {
        city: "Bhālswa Jahangirpur",
        latitude: 28.7354,
        longitude: 77.1638,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "",
        populatitudeion: 151427,
        populatitudeion_proper: 151427
    },
    {
        city: "Nāngloi Jāt",
        latitude: 28.6833,
        longitude: 77.0667,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "",
        populatitudeion: 150371,
        populatitudeion_proper: 150371
    },
    {
        city: "Balasore",
        latitude: 21.5033,
        longitude: 86.925,
        country: "India",
        iso2: "IN",
        admin_name: "Odisha",
        capital: "",
        populatitudeion: 144373,
        populatitudeion_proper: 144373
    },
    {
        city: "Dalūpura",
        latitude: 28.6004,
        longitude: 77.3194,
        country: "India",
        iso2: "IN",
        admin_name: "Delhi",
        capital: "",
        populatitudeion: 132628,
        populatitudeion_proper: 132628
    },
    {
        city: "Yelahanka",
        latitude: 13.1007,
        longitude: 77.5963,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 119891,
        populatitudeion_proper: 119891
    },
    {
        city: "Titāgarh",
        latitude: 22.74,
        longitude: 88.37,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 116541,
        populatitudeion_proper: 116541
    },
    {
        city: "Dam Dam",
        latitude: 22.62,
        longitude: 88.42,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 114786,
        populatitudeion_proper: 114786
    },
    {
        city: "Bānsbāria",
        latitude: 22.97,
        longitude: 88.4,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 103920,
        populatitudeion_proper: 103920
    },
    {
        city: "Madhavaram",
        latitude: 13.1482,
        longitude: 80.2314,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 100442,
        populatitudeion_proper: 100442
    },
    {
        city: "Abbigeri",
        latitude: 13.0767,
        longitude: 77.525,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 100000,
        populatitudeion_proper: 100000
    },
    {
        city: "Baj Baj",
        latitude: 22.4828,
        longitude: 88.1818,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 76837,
        populatitudeion_proper: 76837
    },
    {
        city: "Garhi",
        latitude: 28.6317,
        longitude: 77.3186,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 75544,
        populatitudeion_proper: 75544
    },
    {
        city: "Mīrpeta",
        latitude: 17.32,
        longitude: 78.52,
        country: "India",
        iso2: "IN",
        admin_name: "Telangāna",
        capital: "",
        populatitudeion: 66982,
        populatitudeion_proper: 66982
    },
    {
        city: "Nerkunram",
        latitude: 13.0619,
        longitude: 80.2094,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 52570,
        populatitudeion_proper: 52570
    },
    {
        city: "Kendrāparha",
        latitude: 20.5,
        longitude: 86.42,
        country: "India",
        iso2: "IN",
        admin_name: "Odisha",
        capital: "",
        populatitudeion: 41404,
        populatitudeion_proper: 41404
    },
    {
        city: "Sijua",
        latitude: 23.7762,
        longitude: 86.3303,
        country: "India",
        iso2: "IN",
        admin_name: "Jhārkhand",
        capital: "",
        populatitudeion: 39372,
        populatitudeion_proper: 39372
    },
    {
        city: "Manali",
        latitude: 13.1667,
        longitude: 80.2667,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 37748,
        populatitudeion_proper: 37748
    },
    {
        city: "Kānkuria",
        latitude: 24.6523,
        longitude: 87.9604,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 36925,
        populatitudeion_proper: 36925
    },
    {
        city: "Chakapara",
        latitude: 22.63,
        longitude: 88.35,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 35282,
        populatitudeion_proper: 35282
    },
    {
        city: "Pāppākurichchi",
        latitude: 10.8137,
        longitude: 78.7481,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 26889,
        populatitudeion_proper: 26889
    },
    {
        city: "Herohalli",
        latitude: 12.9911,
        longitude: 77.4873,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 23851,
        populatitudeion_proper: 23851
    },
    {
        city: "Madipakkam",
        latitude: 12.9623,
        longitude: 80.1986,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 20523,
        populatitudeion_proper: 20523
    },
    {
        city: "Sabalpur",
        latitude: 25.6053,
        longitude: 85.1835,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 18810,
        populatitudeion_proper: 18810
    },
    {
        city: "Bāuria",
        latitude: 22.4521,
        longitude: 88.1853,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 16764,
        populatitudeion_proper: 16764
    },
    {
        city: "Salua",
        latitude: 22.61,
        longitude: 88.27,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 15171,
        populatitudeion_proper: 15171
    },
    {
        city: "Chik Bānavar",
        latitude: 13.0846,
        longitude: 77.5014,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 14409,
        populatitudeion_proper: 14409
    },
    {
        city: "Jālhalli",
        latitude: 13.0333,
        longitude: 77.55,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 13063,
        populatitudeion_proper: 13063
    },
    {
        city: "Chinnasekkadu",
        latitude: 13.1609,
        longitude: 80.2573,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 12854,
        populatitudeion_proper: 12854
    },
    {
        city: "Jethuli",
        latitude: 25.5378,
        longitude: 85.2841,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 11572,
        populatitudeion_proper: 11572
    },
    {
        city: "Nagtala",
        latitude: 22.4667,
        longitude: 88.3833,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 10419,
        populatitudeion_proper: 10419
    },
    {
        city: "Pakri",
        latitude: 25.5876,
        longitude: 85.158,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 9768,
        populatitudeion_proper: 9768
    },
    {
        city: "Hunasamaranhalli",
        latitude: 13.1435,
        longitude: 77.62,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 9741,
        populatitudeion_proper: 9741
    },
    {
        city: "Hesarghatta",
        latitude: 13.1391,
        longitude: 77.4783,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 9485,
        populatitudeion_proper: 9485
    },
    {
        city: "Bommayapālaiyam",
        latitude: 11.9922,
        longitude: 79.8499,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 8796,
        populatitudeion_proper: 8796
    },
    {
        city: "Gundūr",
        latitude: 10.7339,
        longitude: 78.7184,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 8587,
        populatitudeion_proper: 8587
    },
    {
        city: "Punādih",
        latitude: 25.5484,
        longitude: 85.2649,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 8273,
        populatitudeion_proper: 8273
    },
    {
        city: "Harilādih",
        latitude: 23.7333,
        longitude: 86.4,
        country: "India",
        iso2: "IN",
        admin_name: "Jhārkhand",
        capital: "",
        populatitudeion: 7917,
        populatitudeion_proper: 7917
    },
    {
        city: "Alāwalpur",
        latitude: 25.4958,
        longitude: 85.2021,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 7827,
        populatitudeion_proper: 7827
    },
    {
        city: "Mādnāikanhalli",
        latitude: 13.0626,
        longitude: 77.4642,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 7805,
        populatitudeion_proper: 7805
    },
    {
        city: "Bāgalūr",
        latitude: 13.133,
        longitude: 77.666,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 7519,
        populatitudeion_proper: 7519
    },
    {
        city: "Kādiganahalli",
        latitude: 13.1687,
        longitude: 77.6283,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 7225,
        populatitudeion_proper: 7225
    },
    {
        city: "Khānpur Zabti",
        latitude: 28.7103,
        longitude: 77.2781,
        country: "India",
        iso2: "IN",
        admin_name: "Uttar Pradesh",
        capital: "",
        populatitudeion: 6994,
        populatitudeion_proper: 6994
    },
    {
        city: "Mahuli",
        latitude: 25.543,
        longitude: 85.2268,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 6683,
        populatitudeion_proper: 6683
    },
    {
        city: "Zeyādah Kot",
        latitude: 22.4445,
        longitude: 88.3345,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 6457,
        populatitudeion_proper: 6457
    },
    {
        city: "Arshakunti",
        latitude: 13.0785,
        longitude: 77.4225,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 6262,
        populatitudeion_proper: 6262
    },
    {
        city: "Mirchi",
        latitude: 25.5554,
        longitude: 85.2139,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 5710,
        populatitudeion_proper: 5710
    },
    {
        city: "Sonudih",
        latitude: 25.1155,
        longitude: 87.0214,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 5658,
        populatitudeion_proper: 5658
    },
    {
        city: "Bayandhalli",
        latitude: 12.9779,
        longitude: 77.5688,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 5118,
        populatitudeion_proper: 5118
    },
    {
        city: "Sondekoppa",
        latitude: 13,
        longitude: 77.3667,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 4866,
        populatitudeion_proper: 4866
    },
    {
        city: "Babura",
        latitude: 25.0851,
        longitude: 87.1092,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 4755,
        populatitudeion_proper: 4755
    },
    {
        city: "Mādavar",
        latitude: 13.0525,
        longitude: 77.4732,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 4678,
        populatitudeion_proper: 4678
    },
    {
        city: "Kadabgeri",
        latitude: 12.9965,
        longitude: 77.4331,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 4573,
        populatitudeion_proper: 4573
    },
    {
        city: "Nanmangalam",
        latitude: 12.9381,
        longitude: 80.1753,
        country: "India",
        iso2: "IN",
        admin_name: "Tamil Nādu",
        capital: "",
        populatitudeion: 4386,
        populatitudeion_proper: 4386
    },
    {
        city: "Taliganja",
        latitude: 22.5041,
        longitude: 88.3598,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 4278,
        populatitudeion_proper: 4278
    },
    {
        city: "Tarchha",
        latitude: 25.1116,
        longitude: 87.0964,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 4198,
        populatitudeion_proper: 4198
    },
    {
        city: "Belgharia",
        latitude: 22.6581,
        longitude: 88.3852,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 4193,
        populatitudeion_proper: 4193
    },
    {
        city: "Kammanhalli",
        latitude: 13.0155,
        longitude: 77.6381,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 4144,
        populatitudeion_proper: 4144
    },
    {
        city: "Ambāpuram",
        latitude: 16.599,
        longitude: 80.8938,
        country: "India",
        iso2: "IN",
        admin_name: "Andhra Pradesh",
        capital: "",
        populatitudeion: 4110,
        populatitudeion_proper: 4110
    },
    {
        city: "Sonnappanhalli",
        latitude: 13.1557,
        longitude: 77.6179,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 3996,
        populatitudeion_proper: 3996
    },
    {
        city: "Kedihāti",
        latitude: 22.6508,
        longitude: 88.4608,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 3910,
        populatitudeion_proper: 3910
    },
    {
        city: "Doddajīvanhalli",
        latitude: 13.0086,
        longitude: 77.6143,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 3792,
        populatitudeion_proper: 3792
    },
    {
        city: "Simli Murārpur",
        latitude: 25.5792,
        longitude: 85.2401,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 3739,
        populatitudeion_proper: 3739
    },
    {
        city: "Sonāwān",
        latitude: 25.5445,
        longitude: 85.2387,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 3682,
        populatitudeion_proper: 3682
    },
    {
        city: "Devanandapur",
        latitude: 22.9326,
        longitude: 88.3729,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 3449,
        populatitudeion_proper: 3449
    },
    {
        city: "Tribeni",
        latitude: 22.9867,
        longitude: 88.3987,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 3305,
        populatitudeion_proper: 3305
    },
    {
        city: "Huttanhalli",
        latitude: 13.1651,
        longitude: 77.6512,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 3240,
        populatitudeion_proper: 3240
    },
    {
        city: "Nathupur",
        latitude: 25.5163,
        longitude: 85.2544,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 3129,
        populatitudeion_proper: 3129
    },
    {
        city: "Bāli",
        latitude: 25.481,
        longitude: 85.2227,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 3128,
        populatitudeion_proper: 3128
    },
    {
        city: "Vājarhalli",
        latitude: 13.1022,
        longitude: 77.4111,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 3009,
        populatitudeion_proper: 3009
    },
    {
        city: "Alija Kotla",
        latitude: 17.2333,
        longitude: 78.55,
        country: "India",
        iso2: "IN",
        admin_name: "Telangāna",
        capital: "",
        populatitudeion: 3000,
        populatitudeion_proper: 3000
    },
    {
        city: "Saino",
        latitude: 25.1134,
        longitude: 87.0108,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2987,
        populatitudeion_proper: 2987
    },
    {
        city: "Shekhpura",
        latitude: 25.5725,
        longitude: 85.1428,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2950,
        populatitudeion_proper: 2950
    },
    {
        city: "Cāchohalli",
        latitude: 13.001,
        longitude: 77.4717,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2946,
        populatitudeion_proper: 2946
    },
    {
        city: "Andheri",
        latitude: 19.2104,
        longitude: 73.0464,
        country: "India",
        iso2: "IN",
        admin_name: "Mahārāshtra",
        capital: "",
        populatitudeion: 2937,
        populatitudeion_proper: 2937
    },
    {
        city: "Nārāyanpur Kola",
        latitude: 25.1293,
        longitude: 87.0076,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2919,
        populatitudeion_proper: 2919
    },
    {
        city: "Gyan Chak",
        latitude: 25.5496,
        longitude: 85.2423,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2855,
        populatitudeion_proper: 2855
    },
    {
        city: "Kasgatpur",
        latitude: 13.1101,
        longitude: 77.5045,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2852,
        populatitudeion_proper: 2852
    },
    {
        city: "Kitanelli",
        latitude: 13.0095,
        longitude: 77.4191,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2827,
        populatitudeion_proper: 2827
    },
    {
        city: "Harchandi",
        latitude: 25.1,
        longitude: 87.0442,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2827,
        populatitudeion_proper: 2827
    },
    {
        city: "Santoshpur",
        latitude: 22.465,
        longitude: 88.2193,
        country: "India",
        iso2: "IN",
        admin_name: "West Bengal",
        capital: "",
        populatitudeion: 2808,
        populatitudeion_proper: 2808
    },
    {
        city: "Bendravādi",
        latitude: 12.3636,
        longitude: 76.9137,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2684,
        populatitudeion_proper: 2684
    },
    {
        city: "Kodagihalli",
        latitude: 12.9771,
        longitude: 77.4651,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2585,
        populatitudeion_proper: 2585
    },
    {
        city: "Harna Buzurg",
        latitude: 25.0981,
        longitude: 87.0148,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2579,
        populatitudeion_proper: 2579
    },
    {
        city: "Mailanhalli",
        latitude: 13.1863,
        longitude: 77.6963,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2543,
        populatitudeion_proper: 2543
    },
    {
        city: "Sultānpur",
        latitude: 25.5248,
        longitude: 85.2507,
        country: "India",
        iso2: "IN",
        admin_name: "Bihār",
        capital: "",
        populatitudeion: 2473,
        populatitudeion_proper: 2473
    },
    {
        city: "Adakimāranhalli",
        latitude: 13.0633,
        longitude: 77.4417,
        country: "India",
        iso2: "IN",
        admin_name: "Karnātaka",
        capital: "",
        populatitudeion: 2453,
        populatitudeion_proper: 2453
    }
];